apiVersion: v1
kind: Secret

metadata:
  name: payload-secret
  namespace: depi4ops

type: Opaque

stringData:
  DATABASE_URL: "mongodb://mongo:27017/StarkOps"
  PAYLOAD_SECRET: "5fc2dc3269d77fcd43e46ef5"